# Generated by Django 3.1 on 2020-08-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField(default='none', max_length=20)),
                ('question', models.CharField(default='none', max_length=150)),
                ('answer', models.TextField(default='none', max_length=50)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='none', max_length=20)),
                ('is_playing', models.BooleanField(default=False)),
                ('level', models.TextField(default='none', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('completedlist', models.TextField(default='', max_length=30)),
            ],
        ),
    ]
