# Generated by Django 3.1 on 2020-09-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='question',
            field=models.TextField(default='none', max_length=150),
        ),
    ]
